# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mySwiftUIApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mySwiftUIApp

    pod ‘Firebase/Core’
    pod ‘Firebase/Database’
    pod ‘Firebase/Auth’
    pod 'Firebase/Firestore'

  target 'mySwiftUIAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mySwiftUIAppUITests' do
    # Pods for testing
  end

end
